"""fix date field in Note

Revision ID: d9a8c8afa2f4
Revises: ab0be29ae8ad
Create Date: 2024-10-12 13:01:36.478711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9a8c8afa2f4'
down_revision: Union[str, None] = 'ab0be29ae8ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
